name: neptune_fob
description: The front end client for Project Neptune.

publish_to: 'none'

version: 0.12.0+1

environment:
  sdk: '>=2.18.5'

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^2.0.2

  provider: ^6.0.5

  biometric_storage: ^4.1.3
  
  image_picker: ^0.8.6+1
  pasteboard: ^0.2.0

  audioplayers: ^4.0.1

  url_launcher: ^6.1.7

  flutter_webrtc: ^0.9.29+hotfix.2

  pointycastle: ^3.7.3
  cryptography: ^2.5.0

  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
      - family: ComicSans
        fonts:
          - asset: fonts/Comic-Sans.ttf
      - family: Consolas
        fonts:
          - asset: fonts/Consolas.ttf
      - family: CenturyGothic
        fonts:
          - asset: fonts/CenturyGothic.ttf
      - family: Helvetica
        fonts:
          - asset: fonts/Helvetica Roman.ttf
      - family: Impact
        fonts:
          - asset: fonts/impact.ttf
  
  assets:
      - assets/message.mp3
